"""add index

Revision ID: e25fb798d76c
Revises: 1d6de2402ba8
Create Date: 2025-04-27 10:47:26.684253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25fb798d76c'
down_revision: Union[str, None] = '1d6de2402ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_weather_data_date'), 'weather_data', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_data_date'), table_name='weather_data')
    # ### end Alembic commands ###
